# Generated by Django 5.1.3 on 2026-04-08 08:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alea', models.CharField(choices=[('attente', 'Attente'), ('deplacement', 'Déplacement inutile'), ('panne', 'Panne machine'), ('manque_matiere', 'Manque matière'), ('rebus', 'Rebus / non-conformité'), ('autre', 'Autre')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('duree', models.PositiveIntegerField(default=0, help_text='Durée en minutes')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GammeOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('temps_alloue', models.PositiveIntegerField(help_text='Durée standard en minutes')),
                ('ordre', models.PositiveSmallIntegerField(help_text='Position dans la gamme')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Operateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('code_badge', models.CharField(max_length=50, unique=True)),
                ('poste', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OperationOF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('bloque', 'Bloqué')], default='en_attente', max_length=20)),
                ('heure_debut', models.DateTimeField(blank=True, null=True)),
                ('heure_fin', models.DateTimeField(blank=True, null=True)),
                ('gamme_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.gammeoperation')),
                ('operateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.operateur')),
            ],
            options={
                'ordering': ['gamme_operation__ordre'],
            },
        ),
        migrations.CreateModel(
            name='OrdreFabrication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('produit', models.CharField(max_length=200)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('date_lancement', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_due', models.DateTimeField(help_text='Date de livraison prévue')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('en_retard', 'En retard'), ('termine', 'Terminé'), ('bloque', 'Bloqué')], default='en_attente', max_length=20)),
                ('gamme', models.ManyToManyField(through='website.OperationOF', to='website.gammeoperation')),
            ],
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.AddField(
            model_name='alea',
            name='declare_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.operateur'),
        ),
        migrations.AddField(
            model_name='alea',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.operationof'),
        ),
        migrations.AddField(
            model_name='operationof',
            name='of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.ordrefabrication'),
        ),
    ]
