# Generated by Django 5.1.3 on 2026-04-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alea_gammeoperation_operateur_operationof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gammeoperation',
            name='temps_alloue',
            field=models.DecimalField(decimal_places=2, help_text='Durée standard en minutes', max_digits=5),
        ),
    ]
