# Generated by Django 5.1.3 on 2026-04-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_gammeoperation_temps_alloue'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='operationof',
            unique_together={('of', 'gamme_operation')},
        ),
        migrations.RemoveField(
            model_name='ordrefabrication',
            name='date_due',
        ),
        migrations.RemoveField(
            model_name='ordrefabrication',
            name='date_lancement',
        ),
        migrations.RemoveField(
            model_name='ordrefabrication',
            name='gamme',
        ),
        migrations.RemoveField(
            model_name='ordrefabrication',
            name='statut',
        ),
        migrations.AddField(
            model_name='operationof',
            name='date_entree',
            field=models.DateTimeField(blank=True, help_text="Date/heure d'ENTRÉE (saisie manuelle)", null=True),
        ),
        migrations.RemoveField(
            model_name='operationof',
            name='heure_debut',
        ),
        migrations.RemoveField(
            model_name='operationof',
            name='heure_fin',
        ),
    ]
