# Generated by Django 5.1.3 on 2026-04-09 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_operationof_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationof',
            name='statut',
        ),
    ]
