# Generated by Django 6.0.4 on 2026-04-20 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_operationof_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gammeoperation',
            name='operateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gammes', to='website.operateur', verbose_name='Opérateur assigné'),
        ),
        migrations.AddField(
            model_name='operateur',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operateur_profil', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur'),
        ),
        migrations.AlterField(
            model_name='gammeoperation',
            name='temps_alloue',
            field=models.DecimalField(decimal_places=4, help_text='Durée en heures (ex: 1.005)', max_digits=7),
        ),
        migrations.CreateModel(
            name='PlanningJournalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('operateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannings', to='website.operateur')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('operateur', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TachePlanifiee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_tache', models.CharField(choices=[('operation', 'Opération de travail'), ('pause_sqa', 'Pause SQA'), ('pause_dejeuner', 'Pause Déjeuner')], max_length=20)),
                ('ordre', models.PositiveSmallIntegerField()),
                ('heure_debut_prevue', models.DateTimeField()),
                ('heure_fin_prevue', models.DateTimeField()),
                ('heure_debut_reelle', models.DateTimeField(blank=True, null=True)),
                ('heure_fin_reelle', models.DateTimeField(blank=True, null=True)),
                ('gamme_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.gammeoperation')),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='website.planningjournalier')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
