# Generated by Django 6.0.4 on 2026-04-21 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_planning_journalier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operateur',
            name='code_badge',
        ),
    ]
