# Generated by Django 6.0.4 on 2026-04-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_operateur_code_badge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gammeoperation',
            name='operateur',
        ),
        migrations.AddField(
            model_name='gammeoperation',
            name='operateurs',
            field=models.ManyToManyField(blank=True, related_name='gammes', to='website.operateur', verbose_name='Opérateurs assignés'),
        ),
    ]
