# Generated by Django 6.0.4 on 2026-04-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_gammeoperation_operateur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operateur',
            name='shift',
            field=models.CharField(choices=[('matin', 'Matin      (06h → 14h)'), ('normal', 'Normal     (08h → 17h)'), ('apres_midi', 'Après-midi (14h → 22h)')], default='normal', max_length=20, verbose_name='Type de shift'),
        ),
    ]
