# Generated by Django 6.0.4 on 2026-05-22 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_operateur_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tacheplanifiee',
            name='heure_debut_reelle',
        ),
    ]
