# Generated by Django 6.0.4 on 2026-05-22 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_tacheplanifiee_heure_debut_reelle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CauseRetard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Retard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree', models.DurationField(help_text='Durée du retard')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description (optionnel)')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('cause', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.causeretard', verbose_name='Cause du retard')),
                ('tache', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.tacheplanifiee')),
            ],
        ),
        migrations.DeleteModel(
            name='Alea',
        ),
    ]
