# Generated by Django 6.0.6 on 2026-06-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_causeretard_retard_delete_alea'),
    ]

    operations = [
        migrations.AddField(
            model_name='operateur',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='operateurs/photos/', verbose_name='Photo de profil'),
        ),
    ]
