# Generated by Django 6.0.6 on 2026-06-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_operateur_photo_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operateur',
            name='poste',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
